### ISSUE TITLE
Incorrect height when using auto size UITableViewCell

### ISSUE THREAD

**Issue by tinpont** [ElaWorkshop/TagListView#88]
It's a little bit difficult to describe this problem, so I create a [demo](https://github.com/tinpont/tag-list-view-problem-demo)(Xcode 8 and Swift 3.0) to show this case.

I using autoLayout to make the TagListView equal to cell's contentView. But the first time load UITableView, you can see UITableViewCell height is not correct.

After scroll out the cell(invisible), and scroll back, the cell shows correctly.

I think this problem may cause by function `intrinsicContentSize`.

**Comment by 651893553** [comment]
I also encountered this problem, what's the solution?

**Comment by tinpont** [comment]
@651893553 TagListView initWithFrame gives cell's width can slove this problem.

**Comment by 651893553** [comment]
@tinpont   Problem has been solved，Thank you very much

**Comment by aleene** [comment]
@tinpont - can you explain this solution a bit more extensively? Might be useful for other users. There was an issue with cellSize and autolayout similar to this bug (not related to TagListView). It seems solved in the latest version of Xcode.

**Comment by tinpont** [comment]
@aleene This problem cause by UITableViewCell first time load with 0 width. So TagListView's `rearrangeViews` function calculate with 0 width(self.frame.width) and return all tags align verticality height.

For example, if TagListView has 3 tags, `intrinsicContentSize` function will return `3 * tagHeight` for tags. So UITableViewCell detect TagListView's height as wrong.

After scroll out and scroll back the cell, `rearrangeViews` function has called by `layoutSubviews` so it can the right width and everything shows correct.

My solution is give cell's width to TagListView so that it can get the right width at first time.

**Comment by aleene** [comment]
Isn't this approach contrary to the idea of autolayout, as you set the width?

**Comment by 651893553** [comment]
@tinpont When I was in the cell dynamically add tagListView height calculation error, has been designated tagListView width, but still have a problem!

**Comment by tinpont** [comment]
@aleene `intrinsicContentSize` function just like telling autoLayout:"At least leave me these space, so that I can show my subviews completely."

@651893553 Try to call cell/cell.contentView `setNeedsLayout` function.

**Comment by aleene** [comment]
I was not happy with the solutions offered here. This works in my demo.

Add:
```
        tableView.estimatedRowHeight = 44.0
        tableView.rowHeight = UITableViewAutomaticDimension
```
In the tableViewController `viewDidLoad()`.

See also: http://stackoverflow.com/questions/18746929/using-auto-layout-in-uitableview-for-dynamic-cell-layouts-variable-row-heights#18746930

**Comment by tinpont** [comment]
@aleene As I know, now tableView will set `rowHeight = UITableViewAutomaticDimension` by default.

At the beginning of this issue, I offer a demo to show this case. In this demo, I already set `rowHeight`. You can run and test for this issue.

**Comment by aleene** [comment]
I have to download your demo, and see what we do differently. Without my solution, I have the same issue as you mentioned.

**Comment by tinpont** [comment]
@aleene My demo already has the code you meation above in ViewController.swift file viewDidLoad function.

**Comment by aleene** [comment]
The more reason to compare the two.

**Comment by aleene** [comment]
I downloaded your demo. And indeed I get the same issue as you: the cellHeight is to large. I copied (some) of your tableView cellForRow code into mine, and I did not get the issue.

The main difference between our demo's is the use of the Storyboard. I use it for the tableView and  tagListView. You do not use a storyboard. I tried to find something in my storyboard, which you might be missing, but could not find it.

So, I can offer no solution.

**Comment by HarukaMa** [comment]
Calling `layoutIfNeeded()` on the cell after dequeuing would fix it.

It may be related to how `UITableView` works on iOS 10. Did you have the same problem in iOS 9?

**Comment by aleene** [comment]
Great, this solves it. I put it in `viewWillAppear()`.

**Comment by tinpont** [comment]
@HarukaMa I only test in iOS 10, create this issue just wanna know if there is a official solution. Thanks  for your suggest.

**Comment by aleene** [comment]
I tested in IOS 10 as well.

**Comment by tinpont** [comment]
Thanks @aleene @HarukaMa, problem solved. Close this issue.

**Comment by nico75005** [comment]
@aleene what did you put in `viewWillAppear()`?
@HarukaMa I called `layoutIfNeeded()` but it doesn't work. I still have to have the cell disappear from the screen and have it appear again.

Do you mind sharing your code please?

This is my code for the tableView:

```
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
	let cell: UITableViewCell
	
	switch indexPath.row {
	default:
		cell = tableView.dequeueReusableCell(withIdentifier: interestTableViewCellIdentifier, for: indexPath) as! TagsTableViewCell
			(cell as! TagsTableViewCell).setTags(demoTags)
		break
	}
	
	cell.layoutIfNeeded()
	
	return cell
}
```

And my cell:

```
class TagsTableViewCell: UITableViewCell {

	@IBOutlet weak var tagListView: TagListView!
	
	
	func setTags(_ tags: [String]) {
		guard tags.count > 0 && tagListView.tagViews.count == 0 else { return }
		
		tagListView.textColor = .mainGreen
		tagListView.borderColor = .mainGreen
		tagListView.borderWidth = 1
		tagListView.paddingX = 10
		tagListView.paddingY = 10
		tagListView.tagBackgroundColor = .clear
		tagListView.textFont = UIFont.robotoRegular(size: 15)
		tagListView.cornerRadius = 15
		tagListView.alignment = .left
		
		for tag in tags {
			tagListView.addTag(tag)
                }
	}
}
```

**Comment by aleene** [comment]
It is sufficient to just add `tableView.estimatedRowHeight = 44.0` to your `viewWillAppear()`.

`tableView.rowHeight = UITableViewAutomaticDimension` or `tableView.layoutIfNeeded()` does not help.

**Comment by annjawn** [comment]
This issue still exists and none of the solution here works in iOS 11. 🙁

**Comment by akdsouza** [comment]
doing the following in the custom cell fixed the issue for me:
`open override func didMoveToSuperview() {
        self.contentView.layoutIfNeeded()
   }`

**Comment by ksathireddy** [comment]
akdsouza you are great. Working fine for me.

**Comment by shkboardfnc** [comment]
TagListView initWithFrame gives cell's width can slove this problem.
ex)
```
tagListView.frame = .init(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 100) // <----
tagListView.snp.makeConstraints { make in
    make.edges.equalToSuperview()
}
tagListView.addTags(tags)
print(tags, self.tagListView.intrinsicContentSize.height)
```

**Comment by Darnell31** [comment]
> [@tinpont](https://github.com/tinpont) Problem has been solved，Thank you very much





https://stackdev.space/questions/why-arent-my-custom-tableview-functions-being-triggered
